
import { SportType } from './types';

export const SPORT_OPTIONS = Object.values(SportType);

export const GENDER_OPTIONS = ['Male', 'Female', 'Other'];

export const DIET_OPTIONS = ['None', 'Vegetarian', 'Vegan', 'Gluten-Free'];

export const ALLERGY_OPTIONS = ['Peanuts', 'Tree Nuts', 'Milk', 'Eggs', 'Soy', 'Wheat', 'Fish', 'Shellfish'];

export const translations = {
  en: {
    appName: 'OptiFuel',
    welcome: 'Welcome',
    dashboard: 'Dashboard',
    nutritionPlan: 'Nutrition Plan',
    eventPlanner: 'Event Planner',
    aiAssistant: 'AI Assistant',
    yourProfile: 'Your Profile',
    premiumFeature: 'Premium Feature',
    upgradePrompt: 'Upgrade to Premium to unlock this feature.',
    getStarted: 'Get Started',
    createProfile: 'Create Your Athlete Profile',
    fullName: 'Full Name',
    age: 'Age',
    gender: 'Gender',
    geographicalArea: 'Geographical Area (e.g., Eldoret, Kenya)',
    height: 'Height (cm)',
    weight: 'Weight (kg)',
    primarySport: 'Primary Sport',
    selectGender: 'Select Gender',
    selectSport: 'Select Sport',
    next: 'Next',
    back: 'Back',
    submit: 'Generate My Plan',
    step: 'Step',
    of: 'of',
    generatingPlan: 'Generating your personalized nutrition plan...',
    planError: 'Could not generate plan. Please try again later.',
    rateLimitError: 'The AI is currently busy. Please try again in a moment.',
    downloadReport: 'Download Report',
    addEvent: 'Add New Event',
    eventName: 'Event Name (e.g., Marathon)',
    eventDate: 'Event Date',
    getRecommendations: 'Get Recommendations',
    recoveryTitle: 'Pre-event & Recovery Nutrition',
    askMeAnything: 'Ask me anything about sports nutrition...',
    sendMessage: 'Send',
    language: 'Language',
    subscription: 'Subscription',
    dailySummary: 'Daily Summary',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fats: 'Fats',
    nutritionistTip: 'Nutritionist\'s Tip',
    breakfast: 'Breakfast',
    midMorningSnack: 'Mid-Morning Snack',
    lunch: 'Lunch',
    afternoonSnack: 'Afternoon Snack',
    dinner: 'Dinner',
    loading1: 'Analyzing your profile...',
    loading2: 'Consulting with our AI nutrition experts...',
    loading3: 'Crafting the perfect meal combinations...',
    loading4: 'Balancing your macros for peak performance...',
    loading5: 'Almost there!',
    listenToTip: 'Listen to Tip',
    readMore: 'Read More',
    close: 'Close',
    mealDetails: 'Meal Details',
    gettingDetails: 'Getting details...',
    ingredients: 'Ingredients',
    preparation: 'Preparation',
    relevantLocations: 'Relevant Locations',
    locationPermission: 'Please enable location access to get localized recommendations.',
    gettingLocation: 'Getting your location...',
    dietaryRestrictions: 'Dietary Restrictions',
    dietType: 'Diet Type',
    selectAllergies: 'Select any allergies',
    otherAllergy: 'Other (please specify)',
    allergyWarningTitle: 'Allergy Alert',
    allergyWarningText: 'Your plan does not account for your specified allergies ({allergies}). Please review all meal ingredients carefully.',
  },
  sw: {
    appName: 'OptiFuel',
    welcome: 'Karibu',
    dashboard: 'Dashibodi',
    nutritionPlan: 'Mpango wa Lishe',
    eventPlanner: 'Mpangaji wa Tukio',
    aiAssistant: 'Msaidizi wa AI',
    yourProfile: 'Wasifu Wako',
    premiumFeature: 'Kipengele cha Premium',
    upgradePrompt: 'Boresha hadi Premium ili kufungua kipengele hiki.',
    getStarted: 'Anza',
    createProfile: 'Unda Wasifu Wako wa Mwanariadha',
    fullName: 'Jina Kamili',
    age: 'Umri',
    gender: 'Jinsia',
    geographicalArea: 'Eneo la Kijiografia (k.m., Eldoret, Kenya)',
    height: 'Urefu (cm)',
    weight: 'Uzito (kg)',
    primarySport: 'Mchezo Mkuu',
    selectGender: 'Chagua Jinsia',
    selectSport: 'Chagua Mchezo',
    next: 'Inayofuata',
    back: 'Nyuma',
    submit: 'Tengeneza Mpango Wangu',
    step: 'Hatua',
    of: 'ya',
    generatingPlan: 'Inatayarisha mpango wako wa lishe...',
    planError: 'Imeshindwa kutengeneza mpango. Tafadhali jaribu tena baadaye.',
    rateLimitError: 'AI ina shughuli nyingi kwa sasa. Tafadhali jaribu tena baada ya muda mfupi.',
    downloadReport: 'Pakua Ripoti',
    addEvent: 'Ongeza Tukio Jipya',
    eventName: 'Jina la Tukio (k.m., Marathon)',
    eventDate: 'Tarehe ya Tukio',
    getRecommendations: 'Pata Mapendekezo',
    recoveryTitle: 'Lishe ya Kabla na Baada ya Tukio',
    askMeAnything: 'Niulize chochote kuhusu lishe ya michezo...',
    sendMessage: 'Tuma',
    language: 'Lugha',
    subscription: 'Usajili',
    dailySummary: 'Muhtasari wa Siku',
    calories: 'Kalori',
    protein: 'Protini',
    carbs: 'Wanga',
    fats: 'Mafuta',
    nutritionistTip: 'Ushauri wa Mtaalamu wa Lishe',
    breakfast: 'Kifungua kinywa',
    midMorningSnack: 'Vitafunio vya Asubuhi',
    lunch: 'Chakula cha mchana',
    afternoonSnack: 'Vitafunio vya Mchana',
    dinner: 'Chakula cha jioni',
    loading1: 'Inachambua wasifu wako...',
    loading2: 'Inawasiliana na wataalamu wetu wa lishe wa AI...',
    loading3: 'Inatayarisha mchanganyiko bora wa milo...',
    loading4: 'Inasawazisha macros zako kwa utendaji wa kilele...',
    loading5: 'Karibu kumaliza!',
    listenToTip: 'Sikiliza Ushauri',
    readMore: 'Soma Zaidi',
    close: 'Funga',
    mealDetails: 'Maelezo ya Mlo',
    gettingDetails: 'Inapata maelezo...',
    ingredients: 'Viungo',
    preparation: 'Matayarisho',
    relevantLocations: 'Maeneo Husika',
    locationPermission: 'Tafadhali ruhusu ufikiaji wa eneo ili kupata mapendekezo ya karibu.',
    gettingLocation: 'Inapata eneo lako...',
    dietaryRestrictions: 'Vizuizi vya Lishe',
    dietType: 'Aina ya Lishe',
    selectAllergies: 'Chagua mizio yoyote',
    otherAllergy: 'Nyingine (tafadhali bainisha)',
    allergyWarningTitle: 'Tahadhari ya Mzio',
    allergyWarningText: 'Mpango wako hauzingatii mizio uliyoainisha ({allergies}). Tafadhali kagua viungo vyote vya mlo kwa makini.',
  }
};